server:
  port: 8080

spring:
  datasource:
    username: root
    password:
    mapper-locations: classpath:/mapper/**/*.xml
    driver: com.mysql.cj.jdbc.Driver
    jdbc-url: jdbc:mysql://localhost:3306/mybatis?serverTimezone=UTC&useUnicode=true&characterEncding=utf8&useSSL=false

mybatis:
  configuration:
    map-underscore-to-camel-case: true
  config-location: classpath:/mybatis/mybatis-config.xml